AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  translator-nodejs

  Sample SAM Template for translator-nodejs
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 6000

Resources:
  TranslatorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: dictionary-handler.lambdaHandler
      Runtime: nodejs20.x
      Timeout: 900
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonDynamoDBReadOnlyAccess
      Architectures:
        - x86_64
      Events:
        Translator:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /translator/{id}
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - handlers/dictionary-handler.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TranslatorApi:
    Description: "API Gateway endpoint URL for Prod stage for Translator function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/translator/"
  TranslatorFunction:
    Description: "Translator Lambda Function ARN"
    Value: !GetAtt TranslatorFunction.Arn
  TranslatorFunctionIamRole:
    Description: "Implicit IAM Role created for Translator function"
    Value: !GetAtt TranslatorFunctionRole.Arn
